# Generated by Django 5.1.5 on 2025-01-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_emp_id_customuser_role_customuser_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
